# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TG8nA7Us7kuFi8OV7sguUnyJDpF8f64w
"""

import time
string=str(input())
wordcount=len(string.split())
print(string)
try:
  while True:
    t0=time.time()
    input_text=str(input("enter the sentence: "))
    t1=time.time()
    accuracy=len(set(input_text.split())&set(string.split()))
    accuracy=accuracy/wordcount
    timetaken=t1-t0
    wpm=wordcount/timetaken
    print("WPM",wpm,"ACCURACY",accuracy,"TIMETAKEN",timetaken)
except KeyboardInterrupt:
  pass
finally:
  print("good")